name: "Helm on EKS (with eksctl)"
description: "Authenticates on EKS clusters using eksctl and executes Helm commands. Can also be used with kubectl commands."
branding:
  icon: 'anchor'
  color: 'blue'
inputs:
    aws-secret-access-key:
        description: 'AWS credentials used to login to eks.'
        required: true
    aws-access-key-id:
        description: 'AWS credentials used to login to eks.'
        required: true
    aws-region:
        description: 'AWS region to use'
        required: true
    cluster-name:
        description: 'EKS cluster name.'
        required: true
outputs:
  result:
    description: "Output returned by your Helm or kubectl command"
runs:
  using: "docker"
  image: "Dockerfile"
  env:
      AWS_REGION: ${{ inputs.aws-region }}
      AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
      AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
      CLUSTER_NAME: ${{ inputs.cluster-name }}
  args:
    - ${{ inputs.command }}
